repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      # Git style
      - id: check-added-large-files
      - id: check-merge-conflict

      # Common errors
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
      - id: check-yaml
      - id: check-merge-conflict

      # Cross platform
      - id: check-case-conflict
      - id: mixed-line-ending
        args: [ --fix=lf ]

      # Security
      - id: detect-aws-credentials
        args: [ '--allow-missing-credentials' ]
      - id: detect-private-key

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.68.0
    hooks:
      - id: terraform_fmt
#      - id: terraform_validate
      - id: terraform_docs
      - id: terraform_tflint
#      - id: terrascan
      - id: terraform_tfsec


#  - repo: https://github.com/terraform-docs/terraform-docs
#    rev: "v0.16.0"
#    hooks:
#      - id: terraform-docs-go
#        args: [ "markdown", "table", "--output-file", "README.md", "./gcp" ]
